# Generated by Django 3.1.5 on 2021-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
